@ECHO OFF
: 
: Interactive Cross-Desktop Group variables.
IF not "%1" == "" SHIFT & GOTO:%1

IF "%XDG_DATA_HOME%" == "" SET "XDG_DATA_HOME=%LOCALAPPDATA%"
IF "%XDG_CONFIG_HOME%" == "" SET "XDG_CONFIG_HOME=%APPDATA%"
IF "%XDG_STATE_HOME%" == "" SET "XDG_STATE_HOME=%LOCALAPPDATA%/.state"
IF not EXIST "%XDG_STATE_HOME%" MKDIR "%XDG_STATE_HOME%" 
IF "%XDG_DATA_DIRS%" == "" SET "XDG_DATA_DIRS=%PROGRAMDATA%"
IF "%XDG_CONFIG_DIRS%" == "" SET "XDG_CONFIG_DIRS=%PROGRAMDATA%/xdg"
IF "%XDG_CACHE_HOME%" == "" SET "XDG_CACHE_HOME=%LOCALAPPDATA%/.cache"
IF not EXIST "%XDG_CACHE_HOME%" MKDIR "%XDG_CACHE_HOME%" 
IF "%XDG_RUNTIME_DIR%" == "" SET "XDG_RUNTIME_DIR=%TEMP%/runtime-%USERSID%"
IF not EXIST "%XDG_RUNTIME_DIR%" MKDIR "%XDG_RUNTIME_DIR%" 

